# Datadog Agent with Logs, APM, Processes, and System Probe enabled

targetSystem: "linux"
datadog:
  # apiKey: <DATADOG_API_KEY>
  # appKey: <DATADOG_APP_KEY>
  apiKeyExistingSecret: datadog-secret
  appKeyExistingSecret: datadog-secret  
  ## The name must be unique and must be dot-separated tokens with the following restrictions:
  ## * Lowercase letters, numbers, and hyphens only.
  ## * Must start with a letter.
  ## * Must end with a number or a letter.
  ## * Overall length should not be higher than 80 characters.
  clusterName: <CLUSTER_NAME>
  site: datadoghq.com
  env:
    - name: DD_APM_COMPUTE_STATS_BY_SPAN_KIND
      value: true 
    - name: DD_APM_PEER_TAGS_AGGREGATION
      value: true
  logs:
    enabled: true
    containerCollectAll: true
    containerCollectUsingFiles: true
  apm:
    portEnabled: false    
    socketEnabled: true  
  processAgent:
    enabled: true
    processCollection: true
  networkMonitoring:
    enabled: true
  serviceMonitoring:
    enabled: true        